package com.example.shikiflow.domain.model.media_details

import com.example.shikiflow.domain.model.auth.AuthType

data class MediaTag(
    val tag: MediaTagEnum,
    val isSpoiler: Boolean = false
)

enum class MediaTagEnum(val supportedBy: Set<AuthType> = setOf(AuthType.ANILIST)) {
    ACHROMATIC,
    ACHRONOLOGICAL_ORDER,
    ACROBATICS,
    ACTING,
    ADOPTION,
    ADULT_CAST(supportedBy = setOf(AuthType.SHIKIMORI)),
    ADVERTISEMENT,
    AFTERLIFE,
    AGE_GAP,
    AGE_REGRESSION,
    AGENDER,
    AGRICULTURE,
    AIRSOFT,
    ALCHEMY,
    ALIENS,
    ALTERNATE_UNIVERSE,
    AMERICAN_FOOTBALL,
    AMNESIA,
    ANACHRONISM,
    ANCIENT_CHINA,
    ANGELS,
    ANIMALS,
    ANTHOLOGY,
    ANTHROPOMORPHIC(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    ANTI_HERO,
    ARCHERY,
    AROMANTIC,
    ARRANGED_MARRIAGE,
    ARTIFICIAL_INTELLIGENCE,
    ASEXUAL,
    ASSASSINS,
    ASTRONOMY,
    ATHLETICS,
    AUGMENTED_REALITY,
    AUTOBIOGRAPHICAL,
    AVIATION,
    AWARD_WINNING(supportedBy = setOf(AuthType.SHIKIMORI)),

    BADMINTON,
    BALLET,
    BAND,
    BAR,
    BASEBALL,
    BASKETBALL,
    BATTLE_ROYALE,
    BIOGRAPHICAL,
    BISEXUAL,
    BLACKMAIL,
    BOARD_GAME,
    BOARDING_SCHOOL,
    BODY_HORROR,
    BODY_IMAGE,
    BODY_SWAPPING,
    BOWLING,
    BOXING,
    BOYS_LOVE,
    BRAINWASHING,
    BULLYING,
    BUTLER,

    CALLIGRAPHY,
    CAMPING,
    CANNIBALISM,
    CARD_BATTLE,
    CARS,
    CENTAUR,
    CGI,
    CHEERLEADING,
    CHIBI,
    CHIMERA,
    CHILDCARE(supportedBy = setOf(AuthType.SHIKIMORI)),
    CHUUNIBYOU,
    CIRCUS,
    CLASS_STRUGGLE,
    CLASSIC_LITERATURE,
    CLASSICAL_MUSIC,
    CLONE,
    COASTAL,
    COHABITATION,
    COLLEGE,
    COMBAT_SPORTS(supportedBy = setOf(AuthType.SHIKIMORI)),
    COMING_OF_AGE,
    CONSPIRACY,
    COSMIC_HORROR,
    COSPLAY,
    COWBOYS,
    CREATURE_TAMING,
    CRIME,
    CROSSDRESSING(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    CROSSOVER,
    CULT,
    CULTIVATION,
    CURSES,
    CUTE_BOYS_DOING_CUTE_THINGS,
    CUTE_GIRLS_DOING_CUTE_THINGS(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    CYBERPUNK,
    CYBORG,
    CYCLING,

    DANCING,
    DEATH_GAME,
    DELINQUENTS(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    DEMONS,
    DENPA,
    DESERT,
    DETECTIVE(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    DINOSAURS,
    DISABILITY,
    DISSOCIATIVE_IDENTITIES,
    DRAGONS,
    DRAWING,
    DRUGS,
    DULLAHAN,
    DUNGEON,
    DYSTOPIAN,

    E_SPORTS,
    ECO_HORROR,
    ECONOMICS,
    EDUCATIONAL(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    ELDERLY_PROTAGONIST,
    ELF,
    ENSEMBLE_CAST,
    ENVIRONMENTAL,
    EPISODIC,
    ERO_GURO,
    ESPIONAGE,
    ESTRANGED_FAMILY,
    EXORCISM,

    FAIRY,
    FAIRY_TALE,
    FAKE_RELATIONSHIP,
    FAMILY_LIFE,
    FASHION,
    FEMALE_HAREM,
    FEMALE_PROTAGONIST,
    FEMBOY,
    FENCING,
    FILMMAKING,
    FIREFIGHTERS,
    FISHING,
    FITNESS,
    FLASH,
    FOOD,
    FOOTBALL,
    FOREIGN,
    FOUND_FAMILY,
    FOUR_KOMA,
    FUGITIVE,
    FULL_CGI,
    FULL_COLOR,

    GAG_HUMOR(supportedBy = setOf(AuthType.SHIKIMORI)),
    GAMBLING,
    GANGS,
    GEKIGA,
    GHOST,
    GO,
    GOBLIN,
    GODS,
    GOLF,
    GORE(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    GRADUATION_PROJECT,
    GUNS,
    GYARU,

    HANDBALL,
    HAREM(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    HENSHIN,
    HETEROSEXUAL,
    HIGH_STAKES_GAME(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    HIKIKOMORI,
    HIP_HOP_MUSIC,
    HISTORICAL(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    HOMELESS,
    HORTICULTURE,
    HUMAN_EXPERIMENTATION,

    ICE_SKATING,
    IDOLS(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    INDIGENOUS_CULTURES,
    INN,
    INTERSPECIES,
    ISEKAI(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    IYASHIKEI(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),

    JAZZ_MUSIC,
    JOSEI(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    JUDO,

    KABUKI,
    KAIJU,
    KARUTA,
    KEMONOMIMI,
    KIDS(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    KINGDOM_MANAGEMENT,
    KONBINI,
    KUUDERE,

    LACROSSE,
    LANGUAGE_BARRIER,
    LGBTQ_PLUS_THEMES,
    LONG_STRIP,
    LOST_CIVILIZATION,
    LOVE_POLYGON(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    LOVE_STATUS_QUO(supportedBy = setOf(AuthType.SHIKIMORI)),

    MAFIA,
    MAGIC,
    GENDER_BENDING(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    MAHOU_SHOUJO(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    MAHJONG,
    MAIDS,
    MAKEUP,
    MALE_HAREM,
    MALE_PROTAGONIST,
    MANZAI,
    MARRIAGE,
    MARTIAL_ARTS(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    MATCHMAKING,
    MATRIARCHY,
    MECHA(supportedBy = setOf(AuthType.SHIKIMORI)),
    MEDICAL(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    MEDICINE,
    MEDIEVAL,
    MEMORY_MANIPULATION,
    MERMAID,
    META,
    METAL_MUSIC,
    MILITARY(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    MIXED_GENDER_HAREM,
    MIXED_MEDIA,
    MODELING,
    MONSTER_BOY,
    MONSTER_GIRL,
    MOPEDS,
    MOTORCYCLES,
    MOUNTAINEERING,
    MUSIC(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    MUSICAL_THEATER,
    MYTHOLOGY(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),

    NATURAL_DISASTER,
    NECROMANCY,
    NEKOMIMI,
    NINJA,
    NO_DIALOGUE,
    NOIR,
    NON_FICTION,
    NUDITY,
    NUN,

    OFFICE,
    OFFICE_LADY,
    OIRAN,
    OJOU_SAMA,
    ORGANIZED_CRIME(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    ORPHAN,
    OTAKU_CULTURE(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    OUTDOOR_ACTIVITIES,

    PANDEMIC,
    PARENTHOOD,
    PARKOUR,
    PARODY(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    PERFORMING_ARTS(supportedBy = setOf(AuthType.SHIKIMORI)),
    PETS(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    PHILOSOPHY,
    PHOTOGRAPHY,
    PIRATES,
    POKER,
    POLICE,
    POLITICS,
    POLYAMOROUS,
    POST_APOCALYPTIC,
    POV,
    PREGNANCY,
    PRIMARILY_ADULT_CAST,
    PRIMARILY_ANIMAL_CAST,
    PRIMARILY_CHILD_CAST,
    PRIMARILY_FEMALE_CAST,
    PRIMARILY_MALE_CAST,
    PRIMARILY_TEEN_CAST,
    PRISON,
    PROXY_BATTLE,
    PSYCHOLOGICAL(supportedBy = setOf(AuthType.SHIKIMORI)),
    PSYCHOSEXUAL,
    PUPPETRY,

    RACING(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    RAKUGO,
    REAL_ROBOT,
    REHABILITATION,
    REINCARNATION(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    RELIGION,
    RESCUE,
    RESTAURANT,
    REVENGE,
    REVERSE_HAREM(supportedBy = setOf(AuthType.SHIKIMORI)),
    REVERSE_ISEKAI,
    ROBOTS,
    ROCK_MUSIC,
    ROTOSCOPING,
    ROYAL_AFFAIRS,
    RUGBY,
    RURAL,

    SAMURAI(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    SATIRE,
    SCHOOL(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    SCHOOL_CLUB,
    SCUBA_DIVING,
    SEINEN(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    SHAPESHIFTING,
    SHIPS,
    SHOGI,
    SHORT_FORM_CHAPTER,
    SHOUJO(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    SHOUNEN(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    SHOWBIZ(supportedBy = setOf(AuthType.SHIKIMORI)),
    SHRINE_MAIDEN,
    SKATEBOARDING,
    SKELETON,
    SLAPSTICK,
    SLAVERY,
    SNOWSCAPE,
    SOFTWARE_DEVELOPMENT,
    SPACE(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    SPACE_OPERA,
    SPEARPLAY,
    STEAMPUNK,
    STOP_MOTION,
    STRATEGY_GAME(supportedBy = setOf(AuthType.SHIKIMORI)),
    SUCCUBUS,
    SUICIDE,
    SUMO,
    SUPER_POWER(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    SUPER_ROBOT,
    SUPERHERO,
    SURFING,
    SURREAL_COMEDY,
    SURVIVAL(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    SWIMMING,
    SWORDPLAY,

    TABLE_TENNIS,
    TANKS,
    TANNED_SKIN,
    TEACHER,
    TEAM_SPORTS(supportedBy = setOf(AuthType.SHIKIMORI)),
    TEENS_LOVE,
    TENNIS,
    TERRORISM,
    TIME_LOOP,
    TIME_MANIPULATION,
    TIME_SKIP,
    TIME_TRAVEL(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    TOKUSATSU,
    TOMBOY,
    TORTURE,
    TRAGEDY,
    TRAINS,
    TRANSGENDER,
    TRAVEL,
    TRIADS,
    TSUNDERE,
    TWINS,

    UNREQUITED_LOVE,
    URBAN,
    URBAN_FANTASY(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),

    VAMPIRE(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    VERTICAL_VIDEO,
    VETERINARIAN,
    VIDEO_GAME(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    VIKINGS,
    VILLAINESS(supportedBy = setOf(AuthType.ANILIST, AuthType.SHIKIMORI)),
    VIRTUAL_WORLD,
    VISUAL_ARTS(supportedBy = setOf(AuthType.SHIKIMORI)),
    VOCAL_SYNTH,
    VOLLEYBALL,
    VTUBER,

    WAR,
    WEREWOLF,
    WILDERNESS,
    WITCH,
    WORK,
    WORKPLACE(supportedBy = setOf(AuthType.SHIKIMORI)),
    WRESTLING,
    WRITING,
    WUXIA,

    YAKUZA,
    YANDERE,
    YOUKAI,
    YURI,
    ZOMBIE
}