package com.example.shikiflow.presentation.common.mappers

import com.example.shikiflow.R
import com.example.shikiflow.domain.model.media_details.MediaTagEnum

object TagMapper {
    fun MediaTagEnum.displayValue(): Int {
        return when(this) {
            MediaTagEnum.ACHROMATIC -> R.string.media_tag_achromatic
            MediaTagEnum.ACHRONOLOGICAL_ORDER -> R.string.media_tag_achronological_order
            MediaTagEnum.ACROBATICS -> R.string.media_tag_acrobatics
            MediaTagEnum.ACTING -> R.string.media_tag_acting
            MediaTagEnum.ADOPTION -> R.string.media_tag_adoption
            MediaTagEnum.ADULT_CAST -> R.string.media_tag_adult_cast
            MediaTagEnum.ADVERTISEMENT -> R.string.media_tag_advertisement
            MediaTagEnum.AFTERLIFE -> R.string.media_tag_afterlife
            MediaTagEnum.AGE_GAP -> R.string.media_tag_age_gap
            MediaTagEnum.AGE_REGRESSION -> R.string.media_tag_age_regression
            MediaTagEnum.AGENDER -> R.string.media_tag_agender
            MediaTagEnum.AGRICULTURE -> R.string.media_tag_agriculture
            MediaTagEnum.AIRSOFT -> R.string.media_tag_airsoft
            MediaTagEnum.ALCHEMY -> R.string.media_tag_alchemy
            MediaTagEnum.ALIENS -> R.string.media_tag_aliens
            MediaTagEnum.ALTERNATE_UNIVERSE -> R.string.media_tag_alternate_universe
            MediaTagEnum.AMERICAN_FOOTBALL -> R.string.media_tag_american_football
            MediaTagEnum.AMNESIA -> R.string.media_tag_amnesia
            MediaTagEnum.ANACHRONISM -> R.string.media_tag_anachronism
            MediaTagEnum.ANCIENT_CHINA -> R.string.media_tag_ancient_china
            MediaTagEnum.ANGELS -> R.string.media_tag_angels
            MediaTagEnum.ANIMALS -> R.string.media_tag_animals
            MediaTagEnum.ANTHOLOGY -> R.string.media_tag_anthology
            MediaTagEnum.ANTHROPOMORPHIC -> R.string.media_tag_anthropomorphic
            MediaTagEnum.ANTI_HERO -> R.string.media_tag_anti_hero
            MediaTagEnum.ARCHERY -> R.string.media_tag_archery
            MediaTagEnum.AROMANTIC -> R.string.media_tag_aromantic
            MediaTagEnum.ARRANGED_MARRIAGE -> R.string.media_tag_arranged_marriage
            MediaTagEnum.ARTIFICIAL_INTELLIGENCE -> R.string.media_tag_artificial_intelligence
            MediaTagEnum.ASEXUAL -> R.string.media_tag_asexual
            MediaTagEnum.ASSASSINS -> R.string.media_tag_assassins
            MediaTagEnum.ASTRONOMY -> R.string.media_tag_astronomy
            MediaTagEnum.ATHLETICS -> R.string.media_tag_athletics
            MediaTagEnum.AUGMENTED_REALITY -> R.string.media_tag_augmented_reality
            MediaTagEnum.AUTOBIOGRAPHICAL -> R.string.media_tag_autobiographical
            MediaTagEnum.AVIATION -> R.string.media_tag_aviation
            MediaTagEnum.AWARD_WINNING -> R.string.media_tag_award_winning
            MediaTagEnum.BADMINTON -> R.string.media_tag_badminton
            MediaTagEnum.BALLET -> R.string.media_tag_ballet
            MediaTagEnum.BAND -> R.string.media_tag_band
            MediaTagEnum.BAR -> R.string.media_tag_bar
            MediaTagEnum.BASEBALL -> R.string.media_tag_baseball
            MediaTagEnum.BASKETBALL -> R.string.media_tag_basketball
            MediaTagEnum.BATTLE_ROYALE -> R.string.media_tag_battle_royale
            MediaTagEnum.BIOGRAPHICAL -> R.string.media_tag_biographical
            MediaTagEnum.BISEXUAL -> R.string.media_tag_bisexual
            MediaTagEnum.BLACKMAIL -> R.string.media_tag_blackmail
            MediaTagEnum.BOARD_GAME -> R.string.media_tag_board_game
            MediaTagEnum.BOARDING_SCHOOL -> R.string.media_tag_boarding_school
            MediaTagEnum.BODY_HORROR -> R.string.media_tag_body_horror
            MediaTagEnum.BODY_IMAGE -> R.string.media_tag_body_image
            MediaTagEnum.BODY_SWAPPING -> R.string.media_tag_body_swapping
            MediaTagEnum.BOWLING -> R.string.media_tag_bowling
            MediaTagEnum.BOXING -> R.string.media_tag_boxing
            MediaTagEnum.BOYS_LOVE -> R.string.media_tag_boys_love
            MediaTagEnum.BRAINWASHING -> R.string.media_tag_brainwashing
            MediaTagEnum.BULLYING -> R.string.media_tag_bullying
            MediaTagEnum.BUTLER -> R.string.media_tag_butler
            MediaTagEnum.CALLIGRAPHY -> R.string.media_tag_calligraphy
            MediaTagEnum.CAMPING -> R.string.media_tag_camping
            MediaTagEnum.CANNIBALISM -> R.string.media_tag_cannibalism
            MediaTagEnum.CARD_BATTLE -> R.string.media_tag_card_battle
            MediaTagEnum.CARS -> R.string.media_tag_cars
            MediaTagEnum.CENTAUR -> R.string.media_tag_centaur
            MediaTagEnum.CGI -> R.string.media_tag_cgi
            MediaTagEnum.CHEERLEADING -> R.string.media_tag_cheerleading
            MediaTagEnum.CHIBI -> R.string.media_tag_chibi
            MediaTagEnum.CHIMERA -> R.string.media_tag_chimera
            MediaTagEnum.CHILDCARE -> R.string.media_tag_childcare
            MediaTagEnum.CHUUNIBYOU -> R.string.media_tag_chuunibyou
            MediaTagEnum.CIRCUS -> R.string.media_tag_circus
            MediaTagEnum.CLASS_STRUGGLE -> R.string.media_tag_class_struggle
            MediaTagEnum.CLASSIC_LITERATURE -> R.string.media_tag_classic_literature
            MediaTagEnum.CLASSICAL_MUSIC -> R.string.media_tag_classical_music
            MediaTagEnum.CLONE -> R.string.media_tag_clone
            MediaTagEnum.COASTAL -> R.string.media_tag_coastal
            MediaTagEnum.COHABITATION -> R.string.media_tag_cohabitation
            MediaTagEnum.COLLEGE -> R.string.media_tag_college
            MediaTagEnum.COMBAT_SPORTS -> R.string.media_tag_combat_sports
            MediaTagEnum.COMING_OF_AGE -> R.string.media_tag_coming_of_age
            MediaTagEnum.CONSPIRACY -> R.string.media_tag_conspiracy
            MediaTagEnum.COSMIC_HORROR -> R.string.media_tag_cosmic_horror
            MediaTagEnum.COSPLAY -> R.string.media_tag_cosplay
            MediaTagEnum.COWBOYS -> R.string.media_tag_cowboys
            MediaTagEnum.CREATURE_TAMING -> R.string.media_tag_creature_taming
            MediaTagEnum.CRIME -> R.string.media_tag_crime
            MediaTagEnum.CROSSDRESSING -> R.string.media_tag_crossdressing
            MediaTagEnum.CROSSOVER -> R.string.media_tag_crossover
            MediaTagEnum.CULT -> R.string.media_tag_cult
            MediaTagEnum.CULTIVATION -> R.string.media_tag_cultivation
            MediaTagEnum.CURSES -> R.string.media_tag_curses
            MediaTagEnum.CUTE_BOYS_DOING_CUTE_THINGS -> R.string.media_tag_cute_boys_doing_cute_things
            MediaTagEnum.CUTE_GIRLS_DOING_CUTE_THINGS -> R.string.media_tag_cute_girls_doing_cute_things
            MediaTagEnum.CYBERPUNK -> R.string.media_tag_cyberpunk
            MediaTagEnum.CYBORG -> R.string.media_tag_cyborg
            MediaTagEnum.CYCLING -> R.string.media_tag_cycling
            MediaTagEnum.DANCING -> R.string.media_tag_dancing
            MediaTagEnum.DEATH_GAME -> R.string.media_tag_death_game
            MediaTagEnum.DELINQUENTS -> R.string.media_tag_delinquents
            MediaTagEnum.DEMONS -> R.string.media_tag_demons
            MediaTagEnum.DENPA -> R.string.media_tag_denpa
            MediaTagEnum.DESERT -> R.string.media_tag_desert
            MediaTagEnum.DETECTIVE -> R.string.media_tag_detective
            MediaTagEnum.DINOSAURS -> R.string.media_tag_dinosaurs
            MediaTagEnum.DISABILITY -> R.string.media_tag_disability
            MediaTagEnum.DISSOCIATIVE_IDENTITIES -> R.string.media_tag_dissociative_identities
            MediaTagEnum.DRAGONS -> R.string.media_tag_dragons
            MediaTagEnum.DRAWING -> R.string.media_tag_drawing
            MediaTagEnum.DRUGS -> R.string.media_tag_drugs
            MediaTagEnum.DULLAHAN -> R.string.media_tag_dullahan
            MediaTagEnum.DUNGEON -> R.string.media_tag_dungeon
            MediaTagEnum.DYSTOPIAN -> R.string.media_tag_dystopian
            MediaTagEnum.E_SPORTS -> R.string.media_tag_e_sports
            MediaTagEnum.ECO_HORROR -> R.string.media_tag_eco_horror
            MediaTagEnum.ECONOMICS -> R.string.media_tag_economics
            MediaTagEnum.EDUCATIONAL -> R.string.media_tag_educational
            MediaTagEnum.ELDERLY_PROTAGONIST -> R.string.media_tag_elderly_protagonist
            MediaTagEnum.ELF -> R.string.media_tag_elf
            MediaTagEnum.ENSEMBLE_CAST -> R.string.media_tag_ensemble_cast
            MediaTagEnum.ENVIRONMENTAL -> R.string.media_tag_environmental
            MediaTagEnum.EPISODIC -> R.string.media_tag_episodic
            MediaTagEnum.ERO_GURO -> R.string.media_tag_ero_guro
            MediaTagEnum.ESPIONAGE -> R.string.media_tag_espionage
            MediaTagEnum.ESTRANGED_FAMILY -> R.string.media_tag_estranged_family
            MediaTagEnum.EXORCISM -> R.string.media_tag_exorcism
            MediaTagEnum.FAIRY -> R.string.media_tag_fairy
            MediaTagEnum.FAIRY_TALE -> R.string.media_tag_fairy_tale
            MediaTagEnum.FAKE_RELATIONSHIP -> R.string.media_tag_fake_relationship
            MediaTagEnum.FAMILY_LIFE -> R.string.media_tag_family_life
            MediaTagEnum.FASHION -> R.string.media_tag_fashion
            MediaTagEnum.FEMALE_HAREM -> R.string.media_tag_female_harem
            MediaTagEnum.FEMALE_PROTAGONIST -> R.string.media_tag_female_protagonist
            MediaTagEnum.FEMBOY -> R.string.media_tag_femboy
            MediaTagEnum.FENCING -> R.string.media_tag_fencing
            MediaTagEnum.FILMMAKING -> R.string.media_tag_filmmaking
            MediaTagEnum.FIREFIGHTERS -> R.string.media_tag_firefighters
            MediaTagEnum.FISHING -> R.string.media_tag_fishing
            MediaTagEnum.FITNESS -> R.string.media_tag_fitness
            MediaTagEnum.FLASH -> R.string.media_tag_flash
            MediaTagEnum.FOOD -> R.string.media_tag_food
            MediaTagEnum.FOOTBALL -> R.string.media_tag_football
            MediaTagEnum.FOREIGN -> R.string.media_tag_foreign
            MediaTagEnum.FOUND_FAMILY -> R.string.media_tag_found_family
            MediaTagEnum.FOUR_KOMA -> R.string.media_tag_four_koma
            MediaTagEnum.FUGITIVE -> R.string.media_tag_fugitive
            MediaTagEnum.FULL_CGI -> R.string.media_tag_full_cgi
            MediaTagEnum.FULL_COLOR -> R.string.media_tag_full_color
            MediaTagEnum.GAG_HUMOR -> R.string.media_tag_gag_humor
            MediaTagEnum.GAMBLING -> R.string.media_tag_gambling
            MediaTagEnum.GANGS -> R.string.media_tag_gangs
            MediaTagEnum.GEKIGA -> R.string.media_tag_gekiga
            MediaTagEnum.GENDER_BENDING -> R.string.media_tag_gender_bending
            MediaTagEnum.GHOST -> R.string.media_tag_ghost
            MediaTagEnum.GO -> R.string.media_tag_go
            MediaTagEnum.GOBLIN -> R.string.media_tag_goblin
            MediaTagEnum.GODS -> R.string.media_tag_gods
            MediaTagEnum.GOLF -> R.string.media_tag_golf
            MediaTagEnum.GORE -> R.string.media_tag_gore
            MediaTagEnum.GRADUATION_PROJECT -> R.string.media_tag_graduation_project
            MediaTagEnum.GUNS -> R.string.media_tag_guns
            MediaTagEnum.GYARU -> R.string.media_tag_gyaru
            MediaTagEnum.HANDBALL -> R.string.media_tag_handball
            MediaTagEnum.HAREM -> R.string.media_tag_harem
            MediaTagEnum.HENSHIN -> R.string.media_tag_henshin
            MediaTagEnum.HETEROSEXUAL -> R.string.media_tag_heterosexual
            MediaTagEnum.HIGH_STAKES_GAME -> R.string.media_tag_high_stakes_game
            MediaTagEnum.HIKIKOMORI -> R.string.media_tag_hikikomori
            MediaTagEnum.HIP_HOP_MUSIC -> R.string.media_tag_hip_hop_music
            MediaTagEnum.HISTORICAL -> R.string.media_tag_historical
            MediaTagEnum.HOMELESS -> R.string.media_tag_homeless
            MediaTagEnum.HORTICULTURE -> R.string.media_tag_horticulture
            MediaTagEnum.HUMAN_EXPERIMENTATION -> R.string.media_tag_human_experimentation
            MediaTagEnum.ICE_SKATING -> R.string.media_tag_ice_skating
            MediaTagEnum.IDOLS -> R.string.media_tag_idols
            MediaTagEnum.INDIGENOUS_CULTURES -> R.string.media_tag_indigenous_cultures
            MediaTagEnum.INN -> R.string.media_tag_inn
            MediaTagEnum.INTERSPECIES -> R.string.media_tag_interspecies
            MediaTagEnum.ISEKAI -> R.string.media_tag_isekai
            MediaTagEnum.IYASHIKEI -> R.string.media_tag_iyashikei
            MediaTagEnum.JAZZ_MUSIC -> R.string.media_tag_jazz_music
            MediaTagEnum.JOSEI -> R.string.media_tag_josei
            MediaTagEnum.JUDO -> R.string.media_tag_judo
            MediaTagEnum.KABUKI -> R.string.media_tag_kabuki
            MediaTagEnum.KAIJU -> R.string.media_tag_kaiju
            MediaTagEnum.KARUTA -> R.string.media_tag_karuta
            MediaTagEnum.KEMONOMIMI -> R.string.media_tag_kemonomimi
            MediaTagEnum.KIDS -> R.string.media_tag_kids
            MediaTagEnum.KINGDOM_MANAGEMENT -> R.string.media_tag_kingdom_management
            MediaTagEnum.KONBINI -> R.string.media_tag_konbini
            MediaTagEnum.KUUDERE -> R.string.media_tag_kuudere
            MediaTagEnum.LACROSSE -> R.string.media_tag_lacrosse
            MediaTagEnum.LANGUAGE_BARRIER -> R.string.media_tag_language_barrier
            MediaTagEnum.LGBTQ_PLUS_THEMES -> R.string.media_tag_lgbtq_plus_themes
            MediaTagEnum.LONG_STRIP -> R.string.media_tag_long_strip
            MediaTagEnum.LOST_CIVILIZATION -> R.string.media_tag_lost_civilization
            MediaTagEnum.LOVE_POLYGON -> R.string.media_tag_love_polygon
            MediaTagEnum.LOVE_STATUS_QUO -> R.string.media_tag_love_status_quo
            MediaTagEnum.MAFIA -> R.string.media_tag_mafia
            MediaTagEnum.MAGIC -> R.string.media_tag_magic
            MediaTagEnum.MAHOU_SHOUJO -> R.string.media_tag_mahou_shoujo
            MediaTagEnum.MAHJONG -> R.string.media_tag_mahjong
            MediaTagEnum.MAIDS -> R.string.media_tag_maids
            MediaTagEnum.MAKEUP -> R.string.media_tag_makeup
            MediaTagEnum.MALE_HAREM -> R.string.media_tag_male_harem
            MediaTagEnum.MALE_PROTAGONIST -> R.string.media_tag_male_protagonist
            MediaTagEnum.MANZAI -> R.string.media_tag_manzai
            MediaTagEnum.MARRIAGE -> R.string.media_tag_marriage
            MediaTagEnum.MARTIAL_ARTS -> R.string.media_tag_martial_arts
            MediaTagEnum.MATCHMAKING -> R.string.media_tag_matchmaking
            MediaTagEnum.MATRIARCHY -> R.string.media_tag_matriarchy
            MediaTagEnum.MECHA -> R.string.media_tag_mecha
            MediaTagEnum.MEDICAL -> R.string.media_tag_medical
            MediaTagEnum.MEDICINE -> R.string.media_tag_medicine
            MediaTagEnum.MEDIEVAL -> R.string.media_tag_medieval
            MediaTagEnum.MEMORY_MANIPULATION -> R.string.media_tag_memory_manipulation
            MediaTagEnum.MERMAID -> R.string.media_tag_mermaid
            MediaTagEnum.META -> R.string.media_tag_meta
            MediaTagEnum.METAL_MUSIC -> R.string.media_tag_metal_music
            MediaTagEnum.MILITARY -> R.string.media_tag_military
            MediaTagEnum.MIXED_GENDER_HAREM -> R.string.media_tag_mixed_gender_harem
            MediaTagEnum.MIXED_MEDIA -> R.string.media_tag_mixed_media
            MediaTagEnum.MODELING -> R.string.media_tag_modeling
            MediaTagEnum.MONSTER_BOY -> R.string.media_tag_monster_boy
            MediaTagEnum.MONSTER_GIRL -> R.string.media_tag_monster_girl
            MediaTagEnum.MOPEDS -> R.string.media_tag_mopeds
            MediaTagEnum.MOTORCYCLES -> R.string.media_tag_motorcycles
            MediaTagEnum.MOUNTAINEERING -> R.string.media_tag_mountaineering
            MediaTagEnum.MUSIC -> R.string.media_tag_music
            MediaTagEnum.MUSICAL_THEATER -> R.string.media_tag_musical_theater
            MediaTagEnum.MYTHOLOGY -> R.string.media_tag_mythology
            MediaTagEnum.NATURAL_DISASTER -> R.string.media_tag_natural_disaster
            MediaTagEnum.NECROMANCY -> R.string.media_tag_necromancy
            MediaTagEnum.NEKOMIMI -> R.string.media_tag_nekomimi
            MediaTagEnum.NINJA -> R.string.media_tag_ninja
            MediaTagEnum.NO_DIALOGUE -> R.string.media_tag_no_dialogue
            MediaTagEnum.NOIR -> R.string.media_tag_noir
            MediaTagEnum.NON_FICTION -> R.string.media_tag_non_fiction
            MediaTagEnum.NUDITY -> R.string.media_tag_nudity
            MediaTagEnum.NUN -> R.string.media_tag_nun
            MediaTagEnum.OFFICE -> R.string.media_tag_office
            MediaTagEnum.OFFICE_LADY -> R.string.media_tag_office_lady
            MediaTagEnum.OIRAN -> R.string.media_tag_oiran
            MediaTagEnum.OJOU_SAMA -> R.string.media_tag_ojou_sama
            MediaTagEnum.ORGANIZED_CRIME -> R.string.media_tag_organized_crime
            MediaTagEnum.ORPHAN -> R.string.media_tag_orphan
            MediaTagEnum.OTAKU_CULTURE -> R.string.media_tag_otaku_culture
            MediaTagEnum.OUTDOOR_ACTIVITIES -> R.string.media_tag_outdoor_activities
            MediaTagEnum.PANDEMIC -> R.string.media_tag_pandemic
            MediaTagEnum.PARENTHOOD -> R.string.media_tag_parenthood
            MediaTagEnum.PARKOUR -> R.string.media_tag_parkour
            MediaTagEnum.PARODY -> R.string.media_tag_parody
            MediaTagEnum.PERFORMING_ARTS -> R.string.media_tag_performing_arts
            MediaTagEnum.PETS -> R.string.media_tag_pets
            MediaTagEnum.PHILOSOPHY -> R.string.media_tag_philosophy
            MediaTagEnum.PHOTOGRAPHY -> R.string.media_tag_photography
            MediaTagEnum.PIRATES -> R.string.media_tag_pirates
            MediaTagEnum.POKER -> R.string.media_tag_poker
            MediaTagEnum.POLICE -> R.string.media_tag_police
            MediaTagEnum.POLITICS -> R.string.media_tag_politics
            MediaTagEnum.POLYAMOROUS -> R.string.media_tag_polyamorous
            MediaTagEnum.POST_APOCALYPTIC -> R.string.media_tag_post_apocalyptic
            MediaTagEnum.POV -> R.string.media_tag_pov
            MediaTagEnum.PREGNANCY -> R.string.media_tag_pregnancy
            MediaTagEnum.PRIMARILY_ADULT_CAST -> R.string.media_tag_primarily_adult_cast
            MediaTagEnum.PRIMARILY_ANIMAL_CAST -> R.string.media_tag_primarily_animal_cast
            MediaTagEnum.PRIMARILY_CHILD_CAST -> R.string.media_tag_primarily_child_cast
            MediaTagEnum.PRIMARILY_FEMALE_CAST -> R.string.media_tag_primarily_female_cast
            MediaTagEnum.PRIMARILY_MALE_CAST -> R.string.media_tag_primarily_male_cast
            MediaTagEnum.PRIMARILY_TEEN_CAST -> R.string.media_tag_primarily_teen_cast
            MediaTagEnum.PRISON -> R.string.media_tag_prison
            MediaTagEnum.PROXY_BATTLE -> R.string.media_tag_proxy_battle
            MediaTagEnum.PSYCHOLOGICAL -> R.string.media_tag_psychological
            MediaTagEnum.PSYCHOSEXUAL -> R.string.media_tag_psychosexual
            MediaTagEnum.PUPPETRY -> R.string.media_tag_puppetry
            MediaTagEnum.RACING -> R.string.media_tag_racing
            MediaTagEnum.RAKUGO -> R.string.media_tag_rakugo
            MediaTagEnum.REAL_ROBOT -> R.string.media_tag_real_robot
            MediaTagEnum.REHABILITATION -> R.string.media_tag_rehabilitation
            MediaTagEnum.REINCARNATION -> R.string.media_tag_reincarnation
            MediaTagEnum.RELIGION -> R.string.media_tag_religion
            MediaTagEnum.RESCUE -> R.string.media_tag_rescue
            MediaTagEnum.RESTAURANT -> R.string.media_tag_restaurant
            MediaTagEnum.REVENGE -> R.string.media_tag_revenge
            MediaTagEnum.REVERSE_HAREM -> R.string.media_tag_reverse_harem
            MediaTagEnum.REVERSE_ISEKAI -> R.string.media_tag_reverse_isekai
            MediaTagEnum.ROBOTS -> R.string.media_tag_robots
            MediaTagEnum.ROCK_MUSIC -> R.string.media_tag_rock_music
            MediaTagEnum.ROTOSCOPING -> R.string.media_tag_rotoscoping
            MediaTagEnum.ROYAL_AFFAIRS -> R.string.media_tag_royal_affairs
            MediaTagEnum.RUGBY -> R.string.media_tag_rugby
            MediaTagEnum.RURAL -> R.string.media_tag_rural
            MediaTagEnum.SAMURAI -> R.string.media_tag_samurai
            MediaTagEnum.SATIRE -> R.string.media_tag_satire
            MediaTagEnum.SCHOOL -> R.string.media_tag_school
            MediaTagEnum.SCHOOL_CLUB -> R.string.media_tag_school_club
            MediaTagEnum.SCUBA_DIVING -> R.string.media_tag_scuba_diving
            MediaTagEnum.SEINEN -> R.string.media_tag_seinen
            MediaTagEnum.SHAPESHIFTING -> R.string.media_tag_shapeshifting
            MediaTagEnum.SHIPS -> R.string.media_tag_ships
            MediaTagEnum.SHOGI -> R.string.media_tag_shogi
            MediaTagEnum.SHORT_FORM_CHAPTER -> R.string.media_tag_short_form_chapter
            MediaTagEnum.SHOUJO -> R.string.media_tag_shoujo
            MediaTagEnum.SHOUNEN -> R.string.media_tag_shounen
            MediaTagEnum.SHOWBIZ -> R.string.media_tag_showbiz
            MediaTagEnum.SHRINE_MAIDEN -> R.string.media_tag_shrine_maiden
            MediaTagEnum.SKATEBOARDING -> R.string.media_tag_skateboarding
            MediaTagEnum.SKELETON -> R.string.media_tag_skeleton
            MediaTagEnum.SLAPSTICK -> R.string.media_tag_slapstick
            MediaTagEnum.SLAVERY -> R.string.media_tag_slavery
            MediaTagEnum.SNOWSCAPE -> R.string.media_tag_snowscape
            MediaTagEnum.SOFTWARE_DEVELOPMENT -> R.string.media_tag_software_development
            MediaTagEnum.SPACE -> R.string.media_tag_space
            MediaTagEnum.SPACE_OPERA -> R.string.media_tag_space_opera
            MediaTagEnum.SPEARPLAY -> R.string.media_tag_spearplay
            MediaTagEnum.STEAMPUNK -> R.string.media_tag_steampunk
            MediaTagEnum.STOP_MOTION -> R.string.media_tag_stop_motion
            MediaTagEnum.STRATEGY_GAME -> R.string.media_tag_strategy_game
            MediaTagEnum.SUCCUBUS -> R.string.media_tag_succubus
            MediaTagEnum.SUICIDE -> R.string.media_tag_suicide
            MediaTagEnum.SUMO -> R.string.media_tag_sumo
            MediaTagEnum.SUPER_POWER -> R.string.media_tag_super_power
            MediaTagEnum.SUPER_ROBOT -> R.string.media_tag_super_robot
            MediaTagEnum.SUPERHERO -> R.string.media_tag_superhero
            MediaTagEnum.SURFING -> R.string.media_tag_surfing
            MediaTagEnum.SURREAL_COMEDY -> R.string.media_tag_surreal_comedy
            MediaTagEnum.SURVIVAL -> R.string.media_tag_survival
            MediaTagEnum.SWIMMING -> R.string.media_tag_swimming
            MediaTagEnum.SWORDPLAY -> R.string.media_tag_swordplay
            MediaTagEnum.TABLE_TENNIS -> R.string.media_tag_table_tennis
            MediaTagEnum.TANKS -> R.string.media_tag_tanks
            MediaTagEnum.TANNED_SKIN -> R.string.media_tag_tanned_skin
            MediaTagEnum.TEACHER -> R.string.media_tag_teacher
            MediaTagEnum.TEAM_SPORTS -> R.string.media_tag_team_sports
            MediaTagEnum.TEENS_LOVE -> R.string.media_tag_teens_love
            MediaTagEnum.TENNIS -> R.string.media_tag_tennis
            MediaTagEnum.TERRORISM -> R.string.media_tag_terrorism
            MediaTagEnum.TIME_LOOP -> R.string.media_tag_time_loop
            MediaTagEnum.TIME_MANIPULATION -> R.string.media_tag_time_manipulation
            MediaTagEnum.TIME_SKIP -> R.string.media_tag_time_skip
            MediaTagEnum.TIME_TRAVEL -> R.string.media_tag_time_travel
            MediaTagEnum.TOKUSATSU -> R.string.media_tag_tokusatsu
            MediaTagEnum.TOMBOY -> R.string.media_tag_tomboy
            MediaTagEnum.TORTURE -> R.string.media_tag_torture
            MediaTagEnum.TRAGEDY -> R.string.media_tag_tragedy
            MediaTagEnum.TRAINS -> R.string.media_tag_trains
            MediaTagEnum.TRANSGENDER -> R.string.media_tag_transgender
            MediaTagEnum.TRAVEL -> R.string.media_tag_travel
            MediaTagEnum.TRIADS -> R.string.media_tag_triads
            MediaTagEnum.TSUNDERE -> R.string.media_tag_tsundere
            MediaTagEnum.TWINS -> R.string.media_tag_twins
            MediaTagEnum.UNREQUITED_LOVE -> R.string.media_tag_unrequited_love
            MediaTagEnum.URBAN -> R.string.media_tag_urban
            MediaTagEnum.URBAN_FANTASY -> R.string.media_tag_urban_fantasy
            MediaTagEnum.VAMPIRE -> R.string.media_tag_vampire
            MediaTagEnum.VERTICAL_VIDEO -> R.string.media_tag_vertical_video
            MediaTagEnum.VETERINARIAN -> R.string.media_tag_veterinarian
            MediaTagEnum.VIDEO_GAME -> R.string.media_tag_video_game
            MediaTagEnum.VIKINGS -> R.string.media_tag_vikings
            MediaTagEnum.VILLAINESS -> R.string.media_tag_villainess
            MediaTagEnum.VIRTUAL_WORLD -> R.string.media_tag_virtual_world
            MediaTagEnum.VISUAL_ARTS -> R.string.media_tag_visual_arts
            MediaTagEnum.VOCAL_SYNTH -> R.string.media_tag_vocal_synth
            MediaTagEnum.VOLLEYBALL -> R.string.media_tag_volleyball
            MediaTagEnum.VTUBER -> R.string.media_tag_vtuber
            MediaTagEnum.WAR -> R.string.media_tag_war
            MediaTagEnum.WEREWOLF -> R.string.media_tag_werewolf
            MediaTagEnum.WILDERNESS -> R.string.media_tag_wilderness
            MediaTagEnum.WITCH -> R.string.media_tag_witch
            MediaTagEnum.WORK -> R.string.media_tag_work
            MediaTagEnum.WORKPLACE -> R.string.media_tag_workplace
            MediaTagEnum.WRESTLING -> R.string.media_tag_wrestling
            MediaTagEnum.WRITING -> R.string.media_tag_writing
            MediaTagEnum.WUXIA -> R.string.media_tag_wuxia
            MediaTagEnum.YAKUZA -> R.string.media_tag_yakuza
            MediaTagEnum.YANDERE -> R.string.media_tag_yandere
            MediaTagEnum.YOUKAI -> R.string.media_tag_youkai
            MediaTagEnum.YURI -> R.string.media_tag_yuri
            MediaTagEnum.ZOMBIE -> R.string.media_tag_zombie
        }
    }
}