name: Android Build with GitHub API Token
run-name: ${{ github.actor }} is building Android app 🚀
on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
jobs:
  Build-Android-App:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        env:
          GITHUB_API_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Build Release APK
        if: startsWith(github.ref, 'refs/tags/')
        run: ./gradlew assembleRelease
        env:
          GITHUB_API_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release.apk
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}