mutation ToggleLike(
    $likeableId: Int!,
    $type: LikeableType!
) {
    ToggleLikeV2(
        id: $likeableId,
        type: $type
    ) {
        ... on ListActivity {
            likeCount
            isLiked
        }
        ... on TextActivity {
            likeCount
            isLiked
        }
        ... on MessageActivity {
            likeCount
            isLiked
        }
        ... on Thread {
            likeCount
            isLiked
        }
        ... on ThreadComment {
            likeCount
            isLiked
        }
        ... on ActivityReply {
            likeCount
            isLiked
        }
    }
}